/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

------------------------------------------------
-- Populate monthly Employer Acccounts Reminder Tasks table --
------------------------------------------------

MERGE [Tasks].[MonthlyReminderTasks] AS target
USING (SELECT NEWID(), 'LevyDeclarationDue', 16, 19, 1) 
	AS source (Id, Type, StartDay, EndDay, ApplicableToApprenticeshipEmployerType)
ON (target.Type = source.Type)
WHEN MATCHED THEN
	UPDATE SET 
		StartDay = source.StartDay,
		EndDay = source.EndDay,
		ApplicableToApprenticeshipEmployerType = source.ApplicableToApprenticeshipEmployerType
WHEN NOT MATCHED THEN 
	INSERT (Id, Type, StartDay, EndDay, ApplicableToApprenticeshipEmployerType)
	VALUES (source.Id, source.Type, source.StartDay, source.EndDay, source.ApplicableToApprenticeshipEmployerType);



-- Tasks backfill --
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=11)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 11, 9)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 9 WHERE Type = 9 and EmployerAccountId = 11  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=15)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 15, 337)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 337 WHERE Type = 9 and EmployerAccountId = 15  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=25)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 25, 96)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 96 WHERE Type = 9 and EmployerAccountId = 25  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=28)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 28, 11)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 11 WHERE Type = 9 and EmployerAccountId = 28  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=312)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 312, 41)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 41 WHERE Type = 9 and EmployerAccountId = 312  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=324)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 324, 7)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 7 WHERE Type = 9 and EmployerAccountId = 324  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=393)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 393, 87)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 87 WHERE Type = 9 and EmployerAccountId = 393  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=660)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 660, 6)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 6 WHERE Type = 9 and EmployerAccountId = 660  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=11324)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 11324, 32)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 32 WHERE Type = 9 and EmployerAccountId = 11324  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=11412)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 11412, 18)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 18 WHERE Type = 9 and EmployerAccountId = 11412  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=11593)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 11593, 14)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 14 WHERE Type = 9 and EmployerAccountId = 11593  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=12188)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 12188, 33)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 33 WHERE Type = 9 and EmployerAccountId = 12188  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=12210)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 12210, 22)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 22 WHERE Type = 9 and EmployerAccountId = 12210  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=12233)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 12233, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 12233  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=12235)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 12235, 6)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 6 WHERE Type = 9 and EmployerAccountId = 12235  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=12675)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 12675, 21)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 21 WHERE Type = 9 and EmployerAccountId = 12675  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=12857)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 12857, 7)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 7 WHERE Type = 9 and EmployerAccountId = 12857  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13164)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13164, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 13164  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13205)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13205, 2)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 2 WHERE Type = 9 and EmployerAccountId = 13205  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13548)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13548, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 13548  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13653)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13653, 8)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 8 WHERE Type = 9 and EmployerAccountId = 13653  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13656)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13656, 2)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 2 WHERE Type = 9 and EmployerAccountId = 13656  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13792)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13792, 112)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 112 WHERE Type = 9 and EmployerAccountId = 13792  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13862)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13862, 5)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 5 WHERE Type = 9 and EmployerAccountId = 13862  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=13979)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 13979, 52)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 52 WHERE Type = 9 and EmployerAccountId = 13979  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=14167)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 14167, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 14167  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=14253)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 14253, 11)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 11 WHERE Type = 9 and EmployerAccountId = 14253  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=14460)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 14460, 29)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 29 WHERE Type = 9 and EmployerAccountId = 14460  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=14607)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 14607, 33)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 33 WHERE Type = 9 and EmployerAccountId = 14607  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=14672)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 14672, 4)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 4 WHERE Type = 9 and EmployerAccountId = 14672  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=15009)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 15009, 9)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 9 WHERE Type = 9 and EmployerAccountId = 15009  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=15145)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 15145, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 15145  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=15637)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 15637, 9)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 9 WHERE Type = 9 and EmployerAccountId = 15637  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=15643)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 15643, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 15643  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=15912)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 15912, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 15912  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=16124)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 16124, 8)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 8 WHERE Type = 9 and EmployerAccountId = 16124  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=16139)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 16139, 6)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 6 WHERE Type = 9 and EmployerAccountId = 16139  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=16511)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 16511, 7)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 7 WHERE Type = 9 and EmployerAccountId = 16511  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=16769)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 16769, 4)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 4 WHERE Type = 9 and EmployerAccountId = 16769  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=16970)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 16970, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 16970  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=17237)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 17237, 7)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 7 WHERE Type = 9 and EmployerAccountId = 17237  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=17239)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 17239, 3)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 3 WHERE Type = 9 and EmployerAccountId = 17239  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=17717)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 17717, 48)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 48 WHERE Type = 9 and EmployerAccountId = 17717  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=17883)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 17883, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 17883  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=18067)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 18067, 19)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 19 WHERE Type = 9 and EmployerAccountId = 18067  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=18157)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 18157, 13)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 13 WHERE Type = 9 and EmployerAccountId = 18157  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=18186)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 18186, 11)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 11 WHERE Type = 9 and EmployerAccountId = 18186  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=18647)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 18647, 3)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 3 WHERE Type = 9 and EmployerAccountId = 18647  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=19466)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 19466, 22)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 22 WHERE Type = 9 and EmployerAccountId = 19466  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=19586)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 19586, 32)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 32 WHERE Type = 9 and EmployerAccountId = 19586  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=20032)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 20032, 12)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 12 WHERE Type = 9 and EmployerAccountId = 20032  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=20131)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 20131, 19)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 19 WHERE Type = 9 and EmployerAccountId = 20131  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=20157)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 20157, 16)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 16 WHERE Type = 9 and EmployerAccountId = 20157  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=20168)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 20168, 2)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 2 WHERE Type = 9 and EmployerAccountId = 20168  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=20248)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 20248, 19)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 19 WHERE Type = 9 and EmployerAccountId = 20248  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=21596)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 21596, 1)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 1 WHERE Type = 9 and EmployerAccountId = 21596  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=22630)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 22630, 33)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 33 WHERE Type = 9 and EmployerAccountId = 22630  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=23275)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 23275, 54)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 54 WHERE Type = 9 and EmployerAccountId = 23275  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=23366)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 23366, 62)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 62 WHERE Type = 9 and EmployerAccountId = 23366  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=24625)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 24625, 13)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 13 WHERE Type = 9 and EmployerAccountId = 24625  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=25502)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 25502, 12)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 12 WHERE Type = 9 and EmployerAccountId = 25502  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=25524)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 25524, 2)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 2 WHERE Type = 9 and EmployerAccountId = 25524  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=25589)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 25589, 9)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 9 WHERE Type = 9 and EmployerAccountId = 25589  
IF NOT EXISTS (select 1 from [Tasks].[Tasks] where [Type]=9 and EmployerAccountId=161492)   INSERT INTO [Tasks].[Tasks] ([Id], [Type], EmployerAccountId, ItemsDueCount) values (NEWID(), 9, 161492, 21)  ELSE   UPDATE [Tasks].[Tasks] set ItemsDueCount = ItemsDueCount + 21 WHERE Type = 9 and EmployerAccountId = 161492  