trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  buildConfiguration: "release"
  buildPlatform: "anycpu"

jobs:
  - job: 'CodeBuild'
    pool: 
      name: 'DAS - Continuous Integration'
    workspace:
      clean: all
    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          updateAssemblyInfo: true

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: "src/**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: "src/**/*.csproj"
          arguments: "--configuration $(buildConfiguration) --no-restore"

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: "**/*Tests.csproj"
          arguments: "--configuration $(buildConfiguration) --no-build"

      - task: DotNetCoreCLI@2
        displayName: "Publish API"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "src/SFA.DAS.Tasks.API/SFA.DAS.Tasks.API.csproj"
          arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build"

      - task: DotNetCoreCLI@2
        displayName: "Publish Web Job"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "src/SFA.DAS.Tasks.Worker/SFA.DAS.Tasks.Worker.csproj"
          arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish/ --no-restore --no-build"
          zipAfterPublish: false
          modifyOutputPath: false
          
      - task: DotNetCoreCLI@2
        displayName: "dotnet pack"
        inputs:
          command: pack
          packagesToPack: >
            src/SFA.DAS.Notifications.Messages/SFA.DAS.Notifications.Messages.csproj
          packDirectory: "$(build.artifactstagingdirectory)/publish"
          versioningScheme: byBuildNumber
          buildProperties: 'Version="$(Build.BuildNumber)"'

      - task: CopyFiles@2
        displayName: "Copy Files to: $(build.artifactstagingdirectory)"
        inputs:
          contents: |
            azure/**
          targetFolder: "$(build.artifactstagingdirectory)/publish"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact"
        inputs:
          pathtoPublish: "$(build.artifactstagingdirectory)/publish"
        
  - job: 'DACPACBuild'
    pool:
      vmImage: 'windows-2019'
    workspace:
      clean: all
    steps:
    - task: VSBuild@1
      displayName: 'Build DACPAC'
      inputs:
        solution: 'src/SFA.DAS.Tasks.Database/SFA.DAS.Tasks.Database.sqlproj'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        contents: |
          src/**/*.dacpac
        targetFolder: '$(build.artifactstagingdirectory)/publish'
        flattenfolders: true
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(build.artifactstagingdirectory)/publish'