parameters:
  SolutionBaseName:
  BuildConfiguration:
  BuildPlatform:

jobs:
- job: AcceptanceTest
  dependsOn: DeployAppsAndDatabase
  pool:
    name: Azure Pipelines
    demands: Agent.OS -equals Windows_NT
    workspace:
      clean: all
  steps:
  - task: VSTest@2
    displayName: Acceptance Tests
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: src\${{ parameters.SolutionBaseName }}.AcceptanceTests\${{ parameters.SolutionBaseName }}.AcceptanceTests.csproj
      configuration: ${{ parameters.BuildConfiguration }}
      platform: ${{ parameters.BuildPlatform }}
