parameters:
  SolutionBaseName:
  BuildConfiguration:
  BuildPlatform:

jobs:
- job: AcceptanceTest
  dependsOn: DeployAppsAndDatabase
  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
    workspace:
      clean: all
  steps:
  - task: NuGetCommand@2
    displayName: Restore
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: '**/*.sln'
      configuration: ${{ parameters.BuildConfiguration }}
      platform: ${{ parameters.BuildPlatform }}

  - task: esfadevops.Tokenization.custom-build-task.Tokenization@0
    displayName: 'Tokenization: Transform file *.config'
    inputs:
      SourcePath: '$(System.DefaultWorkingDirectory)/'
      TargetFileNames: '*.config'
      RequireVariable: true

  - task: VSTest@2
    displayName: Acceptance Tests
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*AcceptanceTests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      configuration: ${{ parameters.BuildConfiguration }}
      platform: ${{ parameters.BuildPlatform }}
