parameters:
  SolutionBaseName:
  BuildConfiguration:
  BuildPlatform:

jobs:
- job: AcceptanceTest
  dependsOn: DeployWebApp
  pool:
    name: DAS - Continuous Integration
    demands: Agent.OS -equals Windows_NT
    workspace:
      clean: all
  steps:
  - download: current
    artifact: ${{ parameters.SolutionBaseName }}
  - task: VSTest@2
    displayName: Acceptance Tests
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.AcceptanceTests/${{ parameters.SolutionBaseName }}.AcceptanceTests.dll
      configuration: ${{ parameters.BuildConfiguration }}
      platform: ${{ parameters.BuildPlatform }}
