parameters:
  SolutionBaseName:
  BuildConfiguration:
  BuildPlatform:

jobs:
- job: CodeBuild
  variables:
  - group: BUILD Management Resources
  steps:
    - task: gitversion/setup@0
      displayName: gitversion/setup
      inputs:
        versionSpec: 5.x

    - task: gitversion/execute@0
      displayName: gitversion/execute
      inputs:
        useConfigFile: true
        configFilePath: GitVersion.yml

    - task: NuGetCommand@2
      displayName: Restore
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'

    - task: VSBuild@1
      displayName: Build
      inputs:
        solution: '**/*.sln'
        configuration: ${{ parameters.BuildConfiguration }}
        platform: ${{ platform.BuildPlatform }}

    - task: VSTest@2
      displayName: Unit Tests
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: | 
          **\*UnitTests.dll
          !**\*TestAdapter.dll
          !**\obj\** 
        configuration: ${{ parameters.BuildConfiguration }}
        platform: ${{ platform.BuildPlatform }}

    ##TO DO: run acceptance tests

    - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

    ##TO DO: publish output

    - task: CopyFiles@2
      displayName: Copy Files to $(build.artifactstagingdirectory)/publish
      inputs:
        Contents: |
          azure/**
        TargetFolder: $(build.artifactstagingdirectory)/publish
        OverWrite: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifact drop
      inputs:
        targetPath: $(build.artifactstagingdirectory)/publish
        artifactName: drop