parameters:
  ConfigurationStorageConnectionString:
  Environment:
  LoggingRedisConnectionString:
  ResourceGroupLocation:
  ServiceConnection:
  SharedStorageAccountConnectionString:
  SubscriptionId:

jobs:
- deployment: DeployWebApp
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)
        - template: azure-pipelines-templates/deploy/step/set-backendaccessrestrictions-variable.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SharedEnvResourceGroup: $(SharedEnvResourceGroup)
            SharedEnvVirtualNetworkName : $(SharedEnvVirtualNetworkName)
            BackEndAccessRestrictionsExcludedSubnets: $(BackEndAccessRestrictionsExcludedSubnets)
            ResourceEnvironmentName: $(ResourceEnvironmentName)
            UnrestrictedEnvironments: $(UnrestrictedEnvironments)
            UptimeMonitoringAccessRestrictions: $(UptimeMonitoringAccessRestrictions)
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: ${{ parameters.SubscriptionId }}
            Location: ${{ parameters.ResourceGroupLocation }}
            Environment: ${{ parameters.Environment }}
            TemplatePath: $(Pipeline.Workspace)/SFA.DAS.Tasks/azure/template.json
            ParametersPath: $(Pipeline.Workspace)/SFA.DAS.Tasks/azure/template.parameters.json
            TemplateSecrets:
              LoggingRedisConnectionString: ${{ parameters.LoggingRedisConnectionString }}
              ConfigurationStorageConnectionString: ${{ parameters.ConfigurationStorageConnectionString }}
              SharedStorageAccountConnectionString: ${{ parameters.SharedStorageAccountConnectionString }}
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-tasks
            TargetFileName: '*.schema.json'
            TableName: Configuration
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(ApiAppServiceName)
            DeploymentPackagePath: $(Pipeline.Workspace)/SFA.DAS.Tasks/SFA.DAS.Tasks.API/SFA.DAS.Tasks.API.zip
